name: "Prototype Groups"
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  validate:
    name: "Validate"
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Compile TypeScript sources
        uses: ./.github/actions/build

      - name: Validate configuration
        run: npm run validate
        env:
          CANVAS_TOKEN: ${{ secrets.CANVAS_TOKEN }}
