name: "Prototype Groups"
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Check"]
    types:
      - completed
  push:
    branches:
      - main

jobs:
  validate:
    name: "Validate"
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}

    permissions:
      contents: read
      actions: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Compile TypeScript sources
        uses: ./.github/actions/build

      - name: Delete existing groups.json
        if: github.event_name == 'workflow_run'
        run: rm ./config/groups.json

      - name: Download PR artifact
        if: github.event_name == 'workflow_run'
        uses: actions/download-artifact@v4
        with:
          name: groups.json
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Validate configuration
        run: npm run validate
        env:
          CANVAS_TOKEN: ${{ secrets.CANVAS_TOKEN }}
